"""
Interactive Friend Recommendation System
=========================================
Run the interactive recommendation system with user prompts.
"""

import sys
import os

# Add project root to path
sys.path.insert(0, os.path.dirname(__file__))

if __name__ == "__main__":
    import pickle
    import random
    from algorithms.graph_generator import generate_social_network
    from algorithms.centrality import compute_pagerank
    from algorithms.recommender import interactive_recommend_friends
    
    print("\n" + "=" * 70)
    print("INTERACTIVE FRIEND RECOMMENDATION SYSTEM")
    print("=" * 70)
    
    # Try to load previously generated graph from main.py
    if os.path.exists('data/generated_graph.pkl'):
        print("\n[1] Loading graph from 'data/generated_graph.pkl'...")
        try:
            with open('data/generated_graph.pkl', 'rb') as f:
                graph = pickle.load(f)
            print(f"    Loaded network with {graph.number_of_nodes()} nodes")
            print(f"    and {graph.number_of_edges()} edges")
            print("    (This is the graph generated by run_analysis.py)")
        except Exception as e:
            print(f"    Failed to load graph: {e}")
            print("    Generating new graph instead...")
            graph = None
    else:
        print("\n[1] No saved graph found (run 'python run_analysis.py' first)")
        print("    Generating new test graph...")
        graph = None
    
    # Generate new graph if loading failed
    if graph is None:
        random.seed(42)
        print("\n[1] Generating social network using Holme-Kim model...")
        graph = generate_social_network(
            num_users=100,
            avg_friends=8,
            community_structure=True,
            num_communities=None  # Auto-calculate
        )
        print(f"    Generated network with {graph.number_of_nodes()} nodes")
        print(f"    and {graph.number_of_edges()} edges")
    
    # Compute PageRank for the network
    print("\n[2] Computing PageRank scores...")
    pagerank_scores = compute_pagerank(graph)
    print(f"    PageRank computed for {len(pagerank_scores)} users")
    
    # Run interactive recommendation system
    print("\n[3] Starting interactive recommendation system...")
    interactive_recommend_friends(graph, pagerank_scores)
